version: '3.9'
services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - ./mysql-db-data:/var/lib/mysql
    networks:
      - app-network

  nodeappmysql:
    build: .
    depends_on:
      - mysqldb
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysqldb
    ports:
      - 8081:80  
    depends_on:
      - mysqldb
    networks:
      - app-network


networks:
  app-network:
